### ISSUE TITLE
Not saving?

### ISSUE THREAD

**Issue by ghost** [artofhuman/activeadmin_settings_cached#11]
Hey,

I followed all steps here but the form is not saving any data, it makes the PUT to the /admin/settings with the data, but it doesn't save.

```
Started PUT "/admin/settings" for 127.0.0.1 at 2015-11-09 14:50:50 -0200
Processing by Admin::SettingsController#index as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"C+dTWWGJ1x6xpAolL/zlfGwKsryptL+K8zJUnWDy2VE=", "settings"=>{"email"=>"test"}, "commit"=>"Salvar Settings"}
  AdminUser Load (1.3ms)  SELECT "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = 1 LIMIT 1
  Settings Load (0.2ms)  SELECT var, value FROM "settings" WHERE "settings"."thing_type" IS NULL AND "settings"."thing_id" IS NULL
  CACHE (0.0ms)  SELECT var, value FROM "settings" WHERE "settings"."thing_type" IS NULL AND "settings"."thing_id" IS NULL
  Rendered /Users/glundgren/.rvm/gems/ruby-2.0.0-p481/gems/activeadmin_settings_cached-1.0.1/app/views/admin/settings/_index.html.erb (9.7ms)
  Rendered /Users/glundgren/.rvm/gems/ruby-2.0.0-p481/gems/activeadmin-0.6.0/app/views/active_admin/page/index.html.arb (63.5ms)
Completed 200 OK in 72ms (Views: 69.0ms | ActiveRecord: 1.5ms)
```

I'm using rails 3.2.8 and ruby 2.0 with this project. Can you give me a clue how can i make it work?

Thank you so much!

**Comment by artofhuman** [comment]
@glundgren Hi, thanks for the report. What version of `rails-settings-cached` you use? I try to reproduce.

**Comment by ghost** [comment]
gem "rails-settings-cached", "0.2.4"

**Comment by ghost** [comment]
i believe it doesn't save because of strong params, i tried to alter the gem in a fork, but couldn't make it work changing the update in controller. had to override the controller in the admin to make it work for me, it was only a quick fix for this project: 

https://github.com/glundgren/activeadmin_settings_cached/commit/a8f38733883ebbed5b564398ea935a057b6094e2?diff=unified

**Comment by artofhuman** [comment]
I think you right. I did not test this gem on rails 3 because it is not supported anymore. Can you try to install `strong_parameters` gem
