### ISSUE TITLE
Incorrect label content and id when using localized attribute names

### ISSUE THREAD

**Issue by nudzg** [artofhuman/activeadmin_settings_cached#13]
Hello,

When using something like this i18n configuration:

<pre>
en:
  settings:
    attributes:
      shipping_europe:
        name: 'Shipping (Europe)'
</pre>

I get this output:

``` html
<label for="settings_Shipping (Europe)">Shipping (europe)</label>
```

I expected this instead:

``` html
<label for="settings_shipping_europe">Shipping (Europe)</label>
```

The corresponding input has id="settings_shipping_europe", so I think there's something wrong.

Fix that makes it work for me:

https://github.com/nudzg/activeadmin_settings_cached/commit/beb4da962f038a53addbc55c1ae5c121280dc481

**Comment by merqlove** [comment]
PR are welcome 👍
