### ISSUE TITLE
Failing travis

### ISSUE THREAD

**Issue by merqlove** [artofhuman/activeadmin_settings_cached#17]
@artofhuman, cheers, 
It looks like Travis bug?

**Comment by artofhuman** [comment]
Maybe, I do not have time to look now. I will to create docker-compose and try to reproduce this errors. And I think about use gem https://github.com/thoughtbot/appraisal to run tests in different  rails versions.

**Comment by merqlove** [comment]
Good idea, AA now supports Rails 5, so it can't be a problem.

**Comment by merqlove** [comment]
Fixed by #27
