### ISSUE TITLE
Error when changing settings without restarting server

### ISSUE THREAD

**Issue by sonololo** [artofhuman/activeadmin_settings_cached#23]
A copy of ActiveadminSettingsCached::DSL has been removed from the module tree but is still active!
```

menu label: 'Settings', priority: 99

  active_admin_settings_page(
    display: {
      'metrika' => :text
    }

```
with the emphasis on  active_admin_settings_page

app/admin/setting.rb:4:in `block in <top (required)>'
app/admin/setting.rb:1:in `<top (required)>'
This error occurred while loading the following files:
   /Users/developer/git_repos/project/app/admin/setting.rb

**Comment by artofhuman** [comment]
Please try version from master, this issue fixed, but the new version has not yet released

**Comment by sonololo** [comment]
Thanks.

Following line

`gem 'activeadmin_settings_cached', github: 'artofhuman/activeadmin_settings_cached'`

fixed it.
