### ISSUE TITLE
A copy of ActiveadminSettingsCached::DSL has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by codehugger** [artofhuman/activeadmin_settings_cached#24]
I have the following code in a file called settings.rb with an underlying model named Setting.

```ruby
ActiveAdmin.register_page 'Settings' do
  active_admin_settings_page
end
```

When I try to access http://localhost:3000/admin/settings I get the following error. Any ideas on how to fix this?

![screen shot 2016-12-13 at 12 11 03](https://cloud.githubusercontent.com/assets/615/21139947/570aef46-c12d-11e6-9db1-4f299f66c4da.png)

And I get this when I restart the Puma server. I am using Rails 5 on Ruby version 2.3.2.

![screen shot 2016-12-13 at 12 17 46](https://cloud.githubusercontent.com/assets/615/21140117/452cf30e-c12e-11e6-8cc4-23f2cbe2c302.png)

**Comment by artofhuman** [comment]
Please see https://github.com/artofhuman/activeadmin_settings_cached/issues/23
Soon I will release a new version
