### ISSUE TITLE
Rails 5: undefined method `map' for #<ActionController::Parameters:0x007f9b695bfcf0> Did you mean? tap

### ISSUE THREAD

**Issue by TangMonk** [artofhuman/activeadmin_settings_cached#34]
When i try to update a setting: 

![image](https://user-images.githubusercontent.com/3498786/28903843-b8347fee-7839-11e7-8c02-748e0066899c.png)

**Comment by TangMonk** [comment]
sorry, I install from the github it will works, please update the rubygems

**Comment by artofhuman** [comment]
@TangMonk thanks for the report, i push new version to rubygems
