### ISSUE TITLE
Strange error after installation

### ISSUE THREAD

**Issue by dareddov** [artofhuman/activeadmin_settings_cached#4]
I have problem with... 
<img width="1680" alt="zrzut ekranu 2015-08-09 o 13 32 06" src="https://cloud.githubusercontent.com/assets/6773940/9154647/2491ceec-3e9b-11e5-9072-d7990549b632.png">

Could somebody help me?

**Comment by artofhuman** [comment]
Can you create repo with app for reproduce this error?

**Comment by dareddov** [comment]
Sure, have you account on BitBucket? Give me your nickname.

**Comment by artofhuman** [comment]
artofhuman
email: semen.pupkov@gmail.com

**Comment by dareddov** [comment]
Sorry, I was on holidays, today I give you access to repo.

**Comment by dareddov** [comment]
Done. @artofhuman

**Comment by artofhuman** [comment]
I see you application.
You does not add routes from readme. You need add routes like this

``` ruby
ActiveAdmin.routes(self)
mount ActiveadminSettingsCached::Engine => '/admin'
```
