### ISSUE TITLE
Breaking changes in dry-types breakes the type coercion

### ISSUE THREAD

**Issue by julfla** [artofhuman/activeadmin_settings_cached#44]
Hello,

I am building a very simple setting form for a project, and update action is failing with an error from dry-container:
> Nothing registered with the key "form.float"

The error happens during coercion  [here](https://github.com/artofhuman/activeadmin_settings_cached/blob/220372bbe90d78204e73c8f18e1a84e06cd12089/lib/activeadmin_settings_cached/coercions.rb#L49) and a breaking change in last dry-types [release 0.13](https://github.com/dry-rb/dry-types/releases) seems to be responsible:

> [BREAKING] Renamed Types::Form to Types::Params. You can opt-in the former name with require 'dry/types/compat/form_types'. It will be dropped in the next release (ndrluis)

The proposed require solves the issue. However, adding constraint _< 0.13.0_ on gem dry-type could be safer.

Even though you plan to remove the dependency on dry-types (#43) would you be interested in a PR?

**Comment by artofhuman** [comment]
@julfla it would be great if you make pr with fix

**Comment by julfla** [comment]
Thanks @artofhuman I created the PR.

**Comment by artofhuman** [comment]
Fixed via https://github.com/artofhuman/activeadmin_settings_cached/pull/45
