### ISSUE TITLE
Аllow use rails-settings-cached with version > 0.6.7

### ISSUE THREAD

**Issue by artofhuman** [artofhuman/activeadmin_settings_cached#49]
Here https://github.com/artofhuman/activeadmin_settings_cached/blob/master/activeadmin_settings_cached.gemspec#L23 we lock   rails-settings-cached < 0.6.7.

Check why and make allow to use all versions

**Comment by Looooong** [comment]
I suppose because this gem relies on features in older version of rails-settings-cached, for example: `Settings.defaults` which is deprecated in 0.6 and is removed in 0.7. This is the problem I am facing when using activeadmin_settings_cached 2.0.0 with rails-settings-cached 0.7.2.

**Comment by fedefa** [comment]
Please reopen this issue, new DSL is really better and used version is old.
