### ISSUE TITLE
Allow use rails-settings-cached > 0.6.7

### ISSUE THREAD

**Issue by artofhuman** [artofhuman/activeadmin_settings_cached#54]

**Comment by m8051** [comment]
Hi @artofhuman, I would like to work on it, would you mind giving me more details? thanks in advance

**Comment by artofhuman** [comment]
Hi, @m8051. I think you can start from this try https://github.com/artofhuman/activeadmin_settings_cached/pull/51/files. Just upgrade dependency and look at the tests. Unfortunately, i dont remember why we are locked rails-settings-cached version.
