### ISSUE TITLE
Rails 3 support

### ISSUE THREAD

**Issue by damdiginess** [artofhuman/activeadmin_settings_cached#9]
The gem with 'rails-settings-cached', '0.2.4' not work.

You can fix it changing

```
settings.defaults.merge!(settings.get_all)
```

to

```
settings.defaults.merge!(settings.all)
```

 in app/admin/settings.rb on line 13.

**Comment by artofhuman** [comment]
@damianogiacomello Thanks for you report.
Please see commit
https://github.com/artofhuman/activeadmin_settings_cached/commit/b692941ece9c256d62bbc627e7df35aa5aa1aa44

This commit include fix for rails 3 and 4.0.x
